version: "3"
services:
  time_manager_api:
    image: teodora27/time_manager_api:latest
    env_file: ./time_manager_api/.env
    build:
      context: ./time_manager_api
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:9.6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  time_manager_front:
    image: teodora27/time_manager_front:latest
    build:
      context: ./time_manager_front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - time_manager_api
    env_file:
      - ./time_manager_front/.env
    volumes:
      - ./time_manager_front:/app

  pgadmin:
    image: dpage/pgadmin4:4.21
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: